@hostName = http://localhost
@port = 8080
@host = {{hostName}}:{{port}}
@apiUrl = {{host}}/api
@gamesApiUrl = {{apiUrl}}/games


### Get All Games
GET {{gamesApiUrl}}


### Get Game by ID
GET {{gamesApiUrl}}/{{currentGameId}}


### Create New Game
# @name newGame
POST {{gamesApiUrl}}/new
Content-Type: application/json

{
}

@currentGameId = {{newGame.response.body.id}}


### Join Player to Current Game
POST {{gamesApiUrl}}/{{currentGameId}}/join
Content-Type: application/json

{
}